### ISSUE TITLE
La suite ?

### ISSUE THREAD

**Issue by benoit-ctrl** [Seb-C/sources-tuto-rpg-openclassrooms#1]
Bonjour,
J'ai suivi ton cours sur openclassrooms, c'était bien écrit et j'ai appris pas mal de truc merci à toi ^^.
As-tu continué le développement du projet du tutoriel ou aurais-tu d'autres projets similaires à me partager ? Je suis curieux de voir à quoi ressemble le système avec les obstacles etc !

Merci par avance.

**Comment by Seb-C** [comment]
Salut, et désolé du délai de réponse.
Malheureusement je n'ai jamais continué ce tuto, je suis passé à autre chose depuis longtemps.
J'avais demandé à ce que quelque chose soit fait sur le site du zéro pour permettre à d'autres de le continuer, mais je n'ai jamais reçu de réponse (déjà qu'il a fallu 6 mois pour que les liens des sources soient mis à jour...). J'ai fini par supprimer mon compte parce que je ne l'utilise plus et je n'ai pas de temps pour répondre à tout le monde.

**Comment by benoit-ctrl** [comment]
Salut,

Merci de ta réponse ^^.

C'est dommage qu'ils ne mettent pas plus en valeur les anciens tutos qui
sont toujours d'actualité...

Bonne continuation :)

Le 28 juillet 2016 à 19:52, Sébastien Caparros notifications@github.com a
écrit :
